Repository hybridapp-io/ham-application-assembler, pull requests merged in 2020-05, with the labels that each got.

#3 upgrade operator sdk to 0.17.0
  common/scripts/install-operator-sdk.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#4 Create deployables
  .gitignore
  deploy/crds/tools.hybridapp.io_applicationassemblers_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  examples/app.yaml
  go.mod
  go.sum
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
  pkg/apis/tools/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/application/application_applicationassembler.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_deployable.go
  pkg/controller/applicationassembler/applicationassembler_controller_test.go
  pkg/controller/applicationassembler/applicationassembler_deployable.go
  pkg/controller/applicationassembler/applicationassembler_generator.go
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: approved, lgtm, size/XL

#5 annotation driven appasm building
  pkg/controller/application/application_applicationassembler.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_status.go
  pkg/controller/applicationassembler/applicationassembler_controller_test.go
  pkg/controller/applicationassembler/applicationassembler_deployable.go
Labels: approved, lgtm, size/L

#6 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#7 fix readme and example
  README.md
  examples/simple.yaml
  go.sum
Labels: approved, lgtm, size/L

#8 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#9 resource discovery reconciliation
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_deployable.go
  pkg/controller/application/application_deployable_test.go
  pkg/controller/application/application_status.go
  pkg/controller/application/application_status_test.go
  pkg/controller/applicationassembler/applicationassembler_controller_test.go
  pkg/controller/applicationassembler/applicationassembler_deployable.go
  pkg/controller/applicationassembler/applicationassembler_deployable_test.go
  pkg/controller/applicationassembler/applicationassembler_generator.go
  pkg/controller/applicationassembler/applicationassembler_object.go
  pkg/controller/applicationassembler/applicationassembler_object_test.go
Labels: approved, lgtm, size/XL

#10 Use discovery labels from ham-deployable-operator
  go.mod
  go.sum
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_status.go
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: approved, lgtm, size/M

#11 ignore managed cluster resource in hub
  pkg/controller/application/application_status.go
Labels: approved, lgtm, size/XS

#12 removed discovery annotation
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
Labels: approved, lgtm, size/XS

#13 Clean up discocvery annotations
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_status.go
Labels: approved, lgtm, size/S

#14 shared hdpl
  pkg/controller/applicationassembler/applicationassembler_object.go
  pkg/controller/applicationassembler/applicationassembler_object_test.go
Labels: approved, lgtm, size/L
