Repository hybridapp-io/ham-application-assembler, pull requests merged in 2020-07, with the labels that each got.

#21 update addMetrics and serveCRMetrics
  cmd/manager/main.go
  go.mod
Labels: approved, lgtm, size/M

#22 deployer scope
  go.mod
  go.sum
  hack/test/core.hybridapp.io_deployers_crd.yaml
  hack/test/core.hybridapp.io_deployersets_crd.yaml
  pkg/controller/applicationassembler/applicationassembler_object.go
  pkg/controller/applicationassembler/applicationassembler_object_test.go
Labels: approved, lgtm, size/XL

#23 Refreshed owners list
  OWNERS
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#24 release-0.0.1
  Makefile
Labels: approved, size/XS
