Repository hybridapp-io/ham-application-assembler, pull requests merged in 2020-11, with the labels that each got.

#34 Fix issue found with gosec
  go.mod
  go.sum
  pkg/controller/application/application_status.go
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: approved, lgtm, size/S

#35 tolerate missing gvk on hub
  pkg/controller/application/application_status.go
Labels: approved, lgtm, size/M

#37 handle null or empty selector
  pkg/controller/application/application_status.go
  pkg/controller/application/application_status_test.go
Labels: approved, lgtm, size/L

#38 clean up the deployable template
  pkg/controller/applicationassembler/applicationassembler_deployable.go
  pkg/controller/applicationassembler/applicationassembler_deployable_test.go
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: approved, lgtm, size/L

#39 cleaning up some unit test
  pkg/controller/applicationassembler/applicationassembler_object_test.go
  pkg/controller/customresourcedefinition/customresourcedefinition_controller_test.go
Labels: approved, lgtm, size/L

#40 additional logging
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: approved, lgtm, size/XS
