Repository hybridapp-io/ham-application-assembler, pull requests merged in 2020-06, with the labels that each got.

#15 Use deployer capabilities for hdpl placement
  pkg/controller/applicationassembler/applicationassembler_object.go
  pkg/controller/applicationassembler/applicationassembler_object_test.go
Labels: approved, lgtm, size/L

#17 Gen name
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
  pkg/controller/applicationassembler/applicationassembler_generator.go
  pkg/controller/applicationassembler/applicationassembler_object_test.go
  pkg/utils/helper.go
Labels: approved, lgtm, size/M

#16 remove bou.ku/monkey
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#18 No requeue for app status update errors
  go.mod
  go.sum
  pkg/controller/application/application_controller.go
Labels: approved, lgtm, size/XS

#19 CRD controller to refresh the gvk map
  pkg/apis/apis.go
  pkg/controller/add_customresourcedefinition.go
  pkg/controller/application/application_controller.go
  pkg/controller/applicationassembler/applicationassembler_controller.go
  pkg/controller/applicationassembler/applicationassembler_object.go
  pkg/controller/customresourcedefinition/customresourcedefinition_controller.go
  pkg/controller/customresourcedefinition/customresourcedefinition_controller_test.go
  pkg/controller/customresourcedefinition/customresourcedefinition_suite_test.go
  pkg/utils/helper.go
Labels: approved, lgtm, size/L
