Repository hybridapp-io/ham-application-assembler, pull requests merged in 2021-03, with the labels that each got.

#49 removed ns from generated hpr
  pkg/controller/applicationassembler/applicationassembler_placementrule.go
Labels: approved, lgtm, size/XS

#50 Remove extra "relationships" from relationships configmap
  pkg/controller/application/application_status.go
  pkg/controller/application/application_status_test.go
Labels: approved, lgtm, size/S

#51 Delete app configmap when app is deleted
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_status.go
  pkg/controller/application/application_status_test.go
Labels: approved, lgtm, size/M

#52 fixed the scc warnings
  pkg/controller/application/application_status.go
Labels: approved, lgtm, size/XS

#53 Fix issue: hybrid-discovery-clusterscoped=false annotation not used
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_status.go
Labels: approved, lgtm, size/L
