Repository hybridapp-io/ham-application-assembler, pull requests merged in 2022-10, with the labels that each got.

#72 Replaced RHACM deployables with manifest works
  go.mod
  go.sum
  hack/test/apps.open-cluster-management.io_deployables_crd.yaml
  hack/test/manifestworks.crd.yaml
  hack/test/work.open-cluster-management.io_manifestworks_crd.yaml
  pkg/apis/apis.go
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
  pkg/controller/application/application_applicationassembler.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_manifestwork.go
  pkg/controller/application/application_manifestwork_test.go
  pkg/controller/application/application_status.go
  pkg/controller/application/application_status_test.go
  pkg/controller/applicationassembler/applicationassembler_controller_test.go
  pkg/controller/applicationassembler/applicationassembler_deployable.go
  pkg/controller/applicationassembler/applicationassembler_deployable_test.go
  pkg/controller/applicationassembler/applicationassembler_generator.go
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: size/XXL, approved, lgtm

#73 Remove references to RHACM subscriptions
  go.mod
  go.sum
  pkg/apis/tools/v1alpha1/applicationassembler_types.go
  pkg/controller/applicationassembler/applicationassembler_object.go
Labels: approved, size/M

#74 update go
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#76 update go modules
  go.mod
  go.sum
Labels: approved, lgtm, size/XS
